dist: trusty
sudo: false
language: python
addons:
  apt:
    packages:
    - libdbus-glib-1-dev
python:
  - "3.5"
  - "3.6"
install:
  - pip install dbus-python
  - python setup.py install
script:
  - pytest
  - timeout 30 selfspy
  - selfstats
