language: python
python:
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - gnupg
      - pass
install:
  # Setup password store keyring
  - gpg -K
  - gpg -k
  - gpg --batch --gen-key tests/gpg-keygen-script
  - gpg -K
  - pass init

  # Installing selfspy
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
  - timeout 30 selfspy --setup
  - selfstats
