language: python
python:
  - "3.5"
  - "3.6"
addons:
  apt:
    packages:
      - gnupg
      - pass
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - pytest
  - timeout 30 selfspy --setup
  - selfstats
