language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install keyrings.alt # Because there is no kwallet on travis
  - python setup.py install
script:
  - pytest
  - timeout 30 selfspy --setup
  - selfstats
